### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by TobiasWeiseX** [fraoustin/piwigo#1]
~~~python
import piwigo
mysite = Piwigo('http://mysite.com')
print(mysite.pwg.getVersion())
~~~

gives me a

NameError: name 'Piwigo' is not defined

which is somewhat obvious... can you add a working example?

**Comment by fraoustin** [comment]
Oups ... it's a mistake

It's necessary use: "from piwigo import Piwigo"
and a site available
